import { getStore } from '@netlify/blobs';
const QUESTIONS=[
{truth:'Accurate'},{truth:'Misleading'},{truth:'Accurate'},{truth:'False'},{truth:'Misleading'},{truth:'Accurate'},{truth:'Misleading'},{truth:'False'}
];
const BET=25_000,LOCK=3_000,REVEAL=10_000,STEP=BET+LOCK+REVEAL,TOTAL=12;
const json=(statusCode,obj)=>({statusCode,headers:{'content-type':'application/json','cache-control':'no-store'},body:JSON.stringify(obj)});
function phaseOf(game,now){if(!game||game.status==='waiting')return{status:'waiting',phase:'waiting',phaseLabel:'Waiting',questionIndex:0,phaseEndsAt:null,phaseProgress:0};const elapsed=now-game.startAt;if(elapsed<0)return{status:'running',phase:'bet',phaseLabel:'Get ready',questionIndex:0,phaseEndsAt:game.startAt,phaseProgress:0};const qi=Math.floor(elapsed/STEP);if(qi>=QUESTIONS.length)return{status:'finished',phase:'finished',phaseLabel:'Finished',questionIndex:QUESTIONS.length-1,phaseEndsAt:null,phaseProgress:1};const within=elapsed%STEP;if(within<BET)return{status:'running',phase:'bet',phaseLabel:'Betting',questionIndex:qi,phaseEndsAt:now+(BET-within),phaseProgress:within/BET};if(within<BET+LOCK)return{status:'running',phase:'lock',phaseLabel:'Locked',questionIndex:qi,phaseEndsAt:now+(BET+LOCK-within),phaseProgress:(within-BET)/LOCK};return{status:'running',phase:'reveal',phaseLabel:'Reveal',questionIndex:qi,phaseEndsAt:now+(STEP-within),phaseProgress:(within-BET-LOCK)/REVEAL}}
async function getGame(store){let g=await store.get('game',{type:'json'});if(!g){g={status:'waiting',gameId:crypto.randomUUID(),createdAt:Date.now()};await store.setJSON('game',g)}return g}
async function listKeys(store,prefix){const out=[];let cursor;do{const r=await store.list({prefix,cursor});out.push(...(r.blobs||[]));cursor=r.cursor}while(cursor);return out}
async function getWallet(store,gameId,playerId){const keys=await listKeys(store,`sub/${gameId}/${playerId}/`);let spent=0,shared=0,score=0;for(const k of keys){const s=await store.get(k.key,{type:'json'});if(!s)continue;spent+=s.coins||0;shared+=s.share?1:0;const truth=QUESTIONS[s.questionIndex]?.truth;if(s.guess===truth)score+=(s.coins||0)*2;else score-=(s.coins||0)}return{coinsLeft:Math.max(0,TOTAL-spent),shareLeft:Math.max(0,1-shared),score}}
async function getSubmission(store,gid,pid,q){return store.get(`sub/${gid}/${pid}/${q}`,{type:'json'})}
async function playerCount(store,gid){return(await listKeys(store,`player/${gid}/`)).length}
async function submittedCount(store,gid,q){const ks=await listKeys(store,`sub/${gid}/`);return ks.filter(x=>x.key.endsWith(`/${q}`)).length}
async function finalStats(store,gid){const pks=await listKeys(store,`player/${gid}/`),sks=await listKeys(store,`sub/${gid}/`);const players=[];for(const p of pks){const obj=await store.get(p.key,{type:'json'});if(obj)players.push(obj)}const subs=[];for(const s of sks){const obj=await store.get(s.key,{type:'json'});if(obj)subs.push(obj)}const eng=QUESTIONS.map((_,i)=>({questionIndex:i,engagement:subs.filter(s=>s.questionIndex===i).reduce((a,s)=>a+(s.coins||0)+(s.share?2:0),0)})).sort((a,b)=>b.engagement-a.engagement);const leaderboard=[];for(const p of players){const w=await getWallet(store,gid,p.playerId);leaderboard.push({name:p.name,score:w.score})}leaderboard.sort((a,b)=>b.score-a.score);return{mostEngaging:eng[0]||null,leaderboard}}
export const handler=async(event)=>{try{const store=getStore('fake-news-auction');const now=Date.now();const playerIdFromQuery=event.queryStringParameters?.playerId||null;let game=await getGame(store);
if(event.httpMethod==='POST'){const b=JSON.parse(event.body||'{}');if(b.action==='reset'){game={status:'waiting',gameId:crypto.randomUUID(),createdAt:now};await store.setJSON('game',game)}
else if(b.action==='start'){game={...game,status:'running',startAt:now+1500};await store.setJSON('game',game)}
else if(b.action==='join'){const name=String(b.name||'').trim().slice(0,24);if(!name)return json(400,{error:'Name required'});if(!b.playerId)return json(400,{error:'Player ID required'});await store.setJSON(`player/${game.gameId}/${b.playerId}`,{playerId:b.playerId,name,joinedAt:now})}
else if(b.action==='submit'){const ph=phaseOf(game,now);if(ph.phase!=='bet'||ph.questionIndex!==b.questionIndex)return json(409,{error:'Betting is closed'});const existing=await getSubmission(store,game.gameId,b.playerId,b.questionIndex);if(existing)return json(409,{error:'Already submitted'});const w=await getWallet(store,game.gameId,b.playerId);const coins=Number(b.coins);if(!Number.isInteger(coins)||coins<0||coins>3||coins>w.coinsLeft)return json(400,{error:'Invalid coin amount'});if(!['Accurate','Misleading','False'].includes(b.guess))return json(400,{error:'Choose Accurate, Misleading or False'});if(b.share&&w.shareLeft<1)return json(400,{error:'Share already used'});await store.setJSON(`sub/${game.gameId}/${b.playerId}/${b.questionIndex}`,{playerId:b.playerId,questionIndex:b.questionIndex,coins,guess:b.guess,share:!!b.share,submittedAt:now})}}
const ph=phaseOf(game,now);const pid=playerIdFromQuery;const base={...ph,serverNow:now,gameId:game.gameId,playerCount:await playerCount(store,game.gameId),submittedCount:ph.status==='running'?await submittedCount(store,game.gameId,ph.questionIndex):0};
if(pid){base.wallet=await getWallet(store,game.gameId,pid);if(ph.status==='running')base.playerSubmission={submitted:!!(await getSubmission(store,game.gameId,pid,ph.questionIndex))}}
if(ph.status==='finished')Object.assign(base,await finalStats(store,game.gameId));return json(200,base)}catch(e){return json(500,{error:e?.message||'Server error'})}}
