import { QUESTIONS, TOTAL_COINS } from './shared.js';
const $=id=>document.getElementById(id);let playerId=localStorage.getItem('fna_player_id')||crypto.randomUUID();localStorage.setItem('fna_player_id',playerId);let joined=localStorage.getItem('fna_joined')==='1';let selectedCoins=null,selectedTruth=null,useShare=false,lastQ=-1;
async function api(method='GET',body=null){const opt={method,headers:{'content-type':'application/json'}};if(body)opt.body=JSON.stringify(body);const suffix=method==='GET'?('?playerId='+encodeURIComponent(playerId)):'';const r=await fetch('/api/game'+suffix,{...opt,cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.json()}
function makeChoices(){const co=$('coinOptions');co.innerHTML='';[0,1,2,3].forEach(n=>{const b=document.createElement('button');b.className='coin';b.textContent=n===0?'0 🪙':`${n} 🪙`;b.onclick=()=>{selectedCoins=n;[...co.children].forEach(x=>x.classList.remove('active'));b.classList.add('active')};co.appendChild(b)});const to=$('truthOptions');to.innerHTML='';[['Accurate','✅ Accurate'],['Misleading','⚠️ Misleading'],['False','❌ False']].forEach(([v,t])=>{const b=document.createElement('button');b.className='truth-btn';b.textContent=t;b.onclick=()=>{selectedTruth=v;[...to.children].forEach(x=>x.classList.remove('active'));b.classList.add('active')};to.appendChild(b)})}makeChoices();
$('joinBtn').onclick=async()=>{const name=$('nameInput').value.trim();if(!name)return;try{await fetch('/api/game',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'join',playerId,name}),cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error(await r.text())});joined=true;localStorage.setItem('fna_joined','1');localStorage.setItem('fna_name',name);$('joinPanel').classList.add('hidden');$('gamePanel').classList.remove('hidden');await tick()}catch(e){alert('Cannot join: '+e.message)}};
if(joined){$('joinPanel').classList.add('hidden');$('gamePanel').classList.remove('hidden')}
$('shareBtn').onclick=()=>{useShare=!useShare;$('shareBtn').classList.toggle('active',useShare);$('shareBtn').textContent=useShare?'🔁 Share selected':'🔁 Use Share (+2 engagement)'};
$('submitBtn').onclick=async()=>{if(selectedCoins===null||!selectedTruth)return alert('Choose coins and a truth guess first.');try{const r=await fetch('/api/game?playerId='+encodeURIComponent(playerId),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'submit',playerId,questionIndex:lastQ,coins:selectedCoins,guess:selectedTruth,share:useShare}),cache:'no-store'});if(!r.ok)throw new Error(await r.text());render(await r.json())}catch(e){alert(e.message)}};
function resetSelection(){selectedCoins=null;selectedTruth=null;useShare=false;[...document.querySelectorAll('.coin,.truth-btn')].forEach(x=>x.classList.remove('active'));$('shareBtn').classList.remove('active');$('shareBtn').textContent='🔁 Use Share (+2 engagement)'}
function renderRoundResult(s){const sub=s.playerSubmission;if(!sub?.submitted){$('roundResult').innerHTML='<b>No bet submitted this round.</b><br>Round score: 0 pts';return;}const sign=sub.scoreDelta>0?'+':'';$('roundResult').innerHTML='<div class="round-big">'+(sub.correct?'Correct! 🎉':'Not quite this time.')+'</div><div>You bet <b>'+sub.coins+' 🪙</b> and chose <b>'+sub.guess+'</b>.</div><div class="round-score">'+sign+sub.scoreDelta+' pts this round</div><div class="round-formula">'+(sub.correct?(sub.coins+' coins × 2'):('−'+sub.coins+' coins'))+'</div><div class="round-total">Total score: <b>'+(s.wallet?.score??0)+'</b> • Coins left: <b>'+(s.wallet?.coinsLeft??0)+'</b></div>';}
function render(s){if(!joined)return;$('phasePill').textContent=s.phaseLabel||'Waiting';$('coinsLeft').textContent=s.wallet?.coinsLeft??TOTAL_COINS;$('shareLeft').textContent=s.wallet?.shareLeft??1;$('score').textContent=s.wallet?.score??0;
if(s.status==='waiting'){$('pqnum').textContent='Lobby';$('pheadline').textContent='Waiting for host…';$('psource').textContent='You are in';$('pteaser').textContent='The game will begin automatically.';$('ptimer').innerHTML='—<small>waiting</small>';$('betArea').classList.add('hidden');$('submittedBox').classList.add('hidden');$('preveal').classList.add('hidden');return}
if(s.status==='finished'){$('gamePanel').classList.add('hidden');$('playerFinal').classList.remove('hidden');$('personalResult').innerHTML=`Your final score: <b>${s.wallet?.score??0} points</b><br>Coins left: ${s.wallet?.coinsLeft??0}`;return}
const q=QUESTIONS[s.questionIndex];if(lastQ!==s.questionIndex){lastQ=s.questionIndex;resetSelection()}$('pqnum').textContent=`Post ${s.questionIndex+1} of ${QUESTIONS.length}`;$('pheadline').textContent=q.headline;$('psource').textContent=q.source;$('pteaser').textContent=q.teaser;const left=Math.max(0,Math.ceil((s.phaseEndsAt-s.serverNow)/1000));if(s.phase==='bet'){$('ptimer').innerHTML=`${left}<small>seconds left</small>`;$('pprogress').style.width=`${Math.max(0,Math.min(100,s.phaseProgress*100))}%`}else{$('ptimer').innerHTML=`RESULT<small>next post soon</small>`;$('pprogress').style.width='100%'}const submitted=s.playerSubmission?.submitted;
if(s.phase==='bet'&&!submitted){$('betArea').classList.remove('hidden');$('submittedBox').classList.add('hidden');$('preveal').classList.add('hidden');[...$('coinOptions').children].forEach((b,i)=>b.disabled=i>(s.wallet?.coinsLeft??0));$('shareBtn').disabled=(s.wallet?.shareLeft??1)<1}else{$('betArea').classList.add('hidden');$('submittedBox').classList.toggle('hidden',!(submitted&&s.phase!=='reveal'))}
if(s.phase==='reveal'){$('submittedBox').classList.add('hidden');$('preveal').className=`reveal ${q.truth}`;$('ptruth').textContent=q.truth==='Accurate'?'✅ ACCURATE':q.truth==='Misleading'?'⚠️ MISLEADING':'❌ FALSE';$('pexplanation').textContent=q.explanation;renderRoundResult(s)}else $('preveal').classList.add('hidden')}
async function tick(){try{render(await api())}catch{$('phasePill').textContent='Reconnect…'}}setInterval(tick,500);tick();
